// Create style element for hiding toolbar buttons
const toolbarStyle = document.createElement('style');
toolbarStyle.textContent = `
    .v-MailboxItem-toolbar,
    .v-MailboxItem:hover .v-MailboxItem-toolbar {
        display: none !important;
        visibility: hidden !important;
        opacity: 0 !important;
    }
`;
document.head.appendChild(toolbarStyle);

// Test that extension is loading
console.log('🔧 Fastmail Fixup extension loaded');

// Create style element for font size
const fontStyle = document.createElement('style');
fontStyle.id = 'fastmail-font-style';
document.head.appendChild(fontStyle);

// Function to update font size
function updateFontSize(fontSize) {
    fontStyle.textContent = `
        .v-Message,
        .v-Message *,
        .v-Message div,
        .v-Message p,
        .v-Message span {
            font-size: ${fontSize}px !important;
        }
    `;
}

// Load and apply saved font size
chrome.storage.sync.get(['fontSize']).then((result) => {
    const savedFontSize = result.fontSize || 18;
    updateFontSize(savedFontSize);
});

// Function to hide CM/ECF automatic message text
function hideCMECFMessage() {
    // Look for message bodies (the actual message content)
    const messageBodies = document.querySelectorAll('.v-Message-body');
    
    if (messageBodies.length === 0) {
        return;
    }
    
    let hiddenCount = 0;
    
    messageBodies.forEach((messageBody, index) => {
        // Look for paragraphs AND pre elements within the message body
        const textElements = messageBody.querySelectorAll('p, pre');
        
        for (let element of textElements) {
            // Skip if already processed
            if (element.hasAttribute('data-cmecf-processed')) continue;
            
            const text = element.textContent.trim();
            
            // For P elements: hide the entire element if it contains only CM/ECF text
            if (element.tagName === 'P' &&
                text.includes("This is an automatic e-mail message generated by the CM/ECF system") &&
                text.includes("***NOTE TO PUBLIC ACCESS USERS***") &&
                text.length < 1500) {
                element.style.display = 'none';
                element.setAttribute('data-cmecf-processed', 'true');
                hiddenCount++;
                continue;
            }
            
            // For PRE elements: remove only the CM/ECF text from the beginning
            if (element.tagName === 'PRE' &&
                text.includes("This is an automatic e-mail message generated by the CM/ECF system") &&
                text.includes("***NOTE TO PUBLIC ACCESS USERS***")) {
                
                console.log('Found PRE with CM/ECF text, processing...');
                
                // Work with innerHTML to preserve HTML structure
                const html = element.innerHTML;
                const disclaimerEnd = "However, if the referenced document is a transcript, the free copy and 30 page limit do not apply.";
                const endIndex = html.indexOf(disclaimerEnd);
                
                if (endIndex !== -1) {
                    // Find content after the disclaimer
                    const afterDisclaimer = html.substring(endIndex + disclaimerEnd.length);
                    
                    // Look for the start of real content (U.S. District Court)
                    const contentStart = afterDisclaimer.indexOf("U.S. District Court");
                    
                    if (contentStart !== -1) {
                        const remainingContent = afterDisclaimer.substring(contentStart).trim();
                        if (remainingContent.length > 0) {
                            element.innerHTML = remainingContent;
                            element.setAttribute('data-cmecf-processed', 'true');
                            hiddenCount++;
                            console.log('✓ Removed CM/ECF disclaimer from PRE element');
                        }
                    } else {
                        // Fallback: just remove everything up to first <br><br>
                        const doubleBreak = afterDisclaimer.indexOf('<br><br>');
                        if (doubleBreak !== -1) {
                            const remainingContent = afterDisclaimer.substring(doubleBreak + 8).trim();
                            if (remainingContent.length > 0) {
                                element.innerHTML = remainingContent;
                                element.setAttribute('data-cmecf-processed', 'true');
                                hiddenCount++;
                                console.log('✓ Removed CM/ECF disclaimer from PRE element (fallback)');
                            }
                        }
                    }
                }
                continue;
            }
        }
        
        // Also check for other elements within the message body for font/b elements
        const allElements = messageBody.querySelectorAll('font, b');
        for (let element of allElements) {
            // Skip if already processed
            if (element.hasAttribute('data-cmecf-hidden')) continue;
            
            const text = element.textContent.trim();
            
            // Pattern 2: Just the "This is an automatic e-mail message..." part (FONT element)
            if (text.includes("This is an automatic e-mail message generated by the CM/ECF system") &&
                text.includes("Please DO NOT RESPOND to this e-mail because the mail box is unattended") &&
                text.length < 300) {
                element.style.display = 'none';
                element.setAttribute('data-cmecf-hidden', 'true');
                hiddenCount++;
                continue;
            }
            
            // Pattern 3: Daily Summary Report notice
            if (text.includes("*** NOTE TO PUBLIC ACCESS USERS ***") &&
                text.includes("This Daily Summary Report may contain documents") &&
                text.includes("Activity has occurred in the following cases:") &&
                text.length < 2000) {
                element.style.display = 'none';
                element.setAttribute('data-cmecf-hidden', 'true');
                hiddenCount++;
                continue;
            }
        }
    });
}

// Run the CM/ECF message hiding function
setTimeout(hideCMECFMessage, 100);
setTimeout(hideCMECFMessage, 500);
setTimeout(hideCMECFMessage, 1000);

// Observe for dynamic content changes more aggressively
const observer = new MutationObserver((mutations) => {
    let shouldCheck = false;
    mutations.forEach((mutation) => {
        if (mutation.type === 'childList' && mutation.addedNodes.length > 0) {
            // Check if any new nodes might contain message content
            for (let node of mutation.addedNodes) {
                if (node.nodeType === Node.ELEMENT_NODE) {
                    // Check for various message-related classes (safely)
                    const nodeClassName = node.className || '';
                    if ((typeof nodeClassName === 'string' && (nodeClassName.includes('Message') || 
                         nodeClassName.includes('Thread') || 
                         nodeClassName.includes('body'))) ||
                        (node.querySelector && (node.querySelector('.v-Message-body') || 
                         node.querySelector('.v-Message') ||
                         node.querySelector('[class*="Message"]')))) {
                        shouldCheck = true;
                        break;
                    }
                }
            }
        }
    });
    if (shouldCheck) {
        setTimeout(hideCMECFMessage, 100);
    }
});

observer.observe(document.body, {
    childList: true,
    subtree: true
});

// Also try to run periodically
setInterval(() => {
    const messageBodies = document.querySelectorAll('.v-Message-body');
    if (messageBodies.length > 0) {
        hideCMECFMessage();
    }
}, 1000);

// Listen for messages from popup
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.action === 'updateFontSize') {
        updateFontSize(message.fontSize);
        sendResponse({ success: true });
    }
});